### ISSUE TITLE
gbif DWCA reader missing ClosableReportingIterator class

### ISSUE THREAD

**Issue by robinkraft** [VertNet/dwca-reader-clj#8]
@tucotuco Looks like the Java code [`get-records`](https://github.com/VertNet/dwca-reader-clj/blob/develop/src/clj/dwca/core.clj#L76-80) is invoking has changed in the latest version of the official DWCA reader. Here's the relevant bit, followed by the full stacktrace that came up while running the [gulo `harvest-resource`](https://github.com/VertNet/gulo/blob/develop/test/gulo/harvest_test.clj#L94-96) test.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/gbif/utils/file/ClosableReportingIterator
...
at org.gbif.file.CSVReaderFactory.build(CSVReaderFactory.java:40)
at org.gbif.dwc.text.ArchiveFile.getCSVReader(ArchiveFile.java:121)
at org.gbif.dwc.text.Archive$ArchiveDwcIterator.<init>(Archive.java:67)
at org.gbif.dwc.text.Archive.iteratorDwc(Archive.java:373)
at dwca.core$get_records.invoke(core.clj:80)
```

I'm not sure where `org/gbif/utils/file/ClosableReportingIterator` should be. What is it being pulled in from? It only shows up [here](https://github.com/gbif/dwca-reader/search?utf8=%E2%9C%93&q=ClosableReportingIterator).

``` text
Exception in thread "main" java.lang.NoClassDefFoundError: org/gbif/utils/file/ClosableReportingIterator
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.gbif.file.CSVReaderFactory.build(CSVReaderFactory.java:40)
    at org.gbif.dwc.text.ArchiveFile.getCSVReader(ArchiveFile.java:121)
    at org.gbif.dwc.text.Archive$ArchiveDwcIterator.<init>(Archive.java:67)
    at org.gbif.dwc.text.Archive.iteratorDwc(Archive.java:373)
    at dwca.core$get_records.invoke(core.clj:80)
    at dwca.core$open.doInvoke(core.clj:99)
    at clojure.lang.RestFn.invoke(RestFn.java:439)
    at gulo.harvest$resource__GT_csv.invoke(harvest.clj:97)
    at gulo.harvest$harvest_resource.invoke(harvest.clj:237)
    at gulo.harvest_test$eval10071$base_function__4623__auto____10072$fn__10073.invoke(harvest_test.clj:94)
    at midje.util.thread_safe_var_nesting$with_altered_roots_STAR_.invoke(thread_safe_var_nesting.clj:32)
    at gulo.harvest_test$eval10071$base_function__4623__auto____10072.invoke(harvest_test.clj:94)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at midje.checking.facts$check_one$fn__4587.invoke(facts.clj:31)
    at midje.checking.facts$check_one.invoke(facts.clj:30)
    at midje.checking.facts$creation_time_check.invoke(facts.clj:35)
    at gulo.harvest_test$eval10071.invoke(harvest_test.clj:94)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.load(Compiler.java:6952)
    at clojure.lang.RT.loadResourceScript(RT.java:359)
    at clojure.lang.RT.loadResourceScript(RT.java:350)
    at clojure.lang.RT.load(RT.java:429)
    at clojure.lang.RT.load(RT.java:400)
    at clojure.core$load$fn__4890.invoke(core.clj:5415)
    at clojure.core$load.doInvoke(core.clj:5414)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5227)
    at clojure.core$load_lib.doInvoke(core.clj:5264)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$load_libs.doInvoke(core.clj:5298)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$require.doInvoke(core.clj:5381)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at midje.repl$load_facts$fn__5701.invoke(repl.clj:206)
    at midje.repl$load_facts.doInvoke(repl.clj:192)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at user$eval5763.invoke(form-init3167297457177487800.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.load(Compiler.java:6952)
    at clojure.lang.Compiler.loadFile(Compiler.java:6912)
    at clojure.main$load_script.invoke(main.clj:283)
    at clojure.main$init_opt.invoke(main.clj:288)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: org.gbif.utils.file.ClosableReportingIterator
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 68 more
Subprocess failed
```

**Comment by tucotuco** [comment]
@robinkraft That's in the gbif-common library at https://github.com/gbif/gbif-common/blob/master/src/main/java/org/gbif/utils/file/ClosableReportingIterator.java.

**Comment by timrobertson100** [comment]
Not sure what your build environment is but all GBIF artifacts are maven ready.  

You can see the required transient dependencies and their versions in [the pom file](http://repository.gbif.org/service/local/repositories/releases/content/org/gbif/dwca-reader/1.18/dwca-reader-1.18.pom).  If you are missing any, we run nexus so [searching for stuff](http://repository.gbif.org/#nexus-search;quick~dwca-reader) should be easy enough.  

Please ping dev@gbif.org if you have issues with any GBIF libs.

**Comment by robinkraft** [comment]
Thanks guys - figured it out. This fixed it.

https://github.com/VertNet/dwca-reader-clj/commit/7858725fc91af2791ef8a012df2bf28be2499b09

**Comment by robinkraft** [comment]
p.s. I just needed to add gbif-common to the dependencies. I'm not sure why we didn't need it before, but things seem to be ok.
